// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/cli.proto

package cli

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/mhchlib/mconfig-api/api/v1/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PutMconfigRequest struct {
	AppKey               string              `protobuf:"bytes,1,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	ConfigKey            string              `protobuf:"bytes,2,opt,name=config_key,json=configKey,proto3" json:"config_key,omitempty"`
	Schema               string              `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	Config               string              `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	AbFilter             string              `protobuf:"bytes,5,opt,name=ab_filter,json=abFilter,proto3" json:"ab_filter,omitempty"`
	Status               common.ConfigStatus `protobuf:"varint,6,opt,name=status,proto3,enum=api.common.ConfigStatus" json:"status,omitempty"`
	Desc                 string              `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PutMconfigRequest) Reset()         { *m = PutMconfigRequest{} }
func (m *PutMconfigRequest) String() string { return proto.CompactTextString(m) }
func (*PutMconfigRequest) ProtoMessage()    {}
func (*PutMconfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1717ceaaafb7e16a, []int{0}
}

func (m *PutMconfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutMconfigRequest.Unmarshal(m, b)
}
func (m *PutMconfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutMconfigRequest.Marshal(b, m, deterministic)
}
func (m *PutMconfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutMconfigRequest.Merge(m, src)
}
func (m *PutMconfigRequest) XXX_Size() int {
	return xxx_messageInfo_PutMconfigRequest.Size(m)
}
func (m *PutMconfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutMconfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutMconfigRequest proto.InternalMessageInfo

func (m *PutMconfigRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *PutMconfigRequest) GetConfigKey() string {
	if m != nil {
		return m.ConfigKey
	}
	return ""
}

func (m *PutMconfigRequest) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func (m *PutMconfigRequest) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

func (m *PutMconfigRequest) GetAbFilter() string {
	if m != nil {
		return m.AbFilter
	}
	return ""
}

func (m *PutMconfigRequest) GetStatus() common.ConfigStatus {
	if m != nil {
		return m.Status
	}
	return common.ConfigStatus_Unpublished
}

func (m *PutMconfigRequest) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type PutMconfigResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutMconfigResponse) Reset()         { *m = PutMconfigResponse{} }
func (m *PutMconfigResponse) String() string { return proto.CompactTextString(m) }
func (*PutMconfigResponse) ProtoMessage()    {}
func (*PutMconfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1717ceaaafb7e16a, []int{1}
}

func (m *PutMconfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutMconfigResponse.Unmarshal(m, b)
}
func (m *PutMconfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutMconfigResponse.Marshal(b, m, deterministic)
}
func (m *PutMconfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutMconfigResponse.Merge(m, src)
}
func (m *PutMconfigResponse) XXX_Size() int {
	return xxx_messageInfo_PutMconfigResponse.Size(m)
}
func (m *PutMconfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutMconfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutMconfigResponse proto.InternalMessageInfo

func (m *PutMconfigResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PutMconfigResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type InitMconfigAppRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	AppDesc              string   `protobuf:"bytes,2,opt,name=app_desc,json=appDesc,proto3" json:"app_desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitMconfigAppRequest) Reset()         { *m = InitMconfigAppRequest{} }
func (m *InitMconfigAppRequest) String() string { return proto.CompactTextString(m) }
func (*InitMconfigAppRequest) ProtoMessage()    {}
func (*InitMconfigAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1717ceaaafb7e16a, []int{2}
}

func (m *InitMconfigAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitMconfigAppRequest.Unmarshal(m, b)
}
func (m *InitMconfigAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitMconfigAppRequest.Marshal(b, m, deterministic)
}
func (m *InitMconfigAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitMconfigAppRequest.Merge(m, src)
}
func (m *InitMconfigAppRequest) XXX_Size() int {
	return xxx_messageInfo_InitMconfigAppRequest.Size(m)
}
func (m *InitMconfigAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitMconfigAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitMconfigAppRequest proto.InternalMessageInfo

func (m *InitMconfigAppRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *InitMconfigAppRequest) GetAppDesc() string {
	if m != nil {
		return m.AppDesc
	}
	return ""
}

type InitMconfigAppResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitMconfigAppResponse) Reset()         { *m = InitMconfigAppResponse{} }
func (m *InitMconfigAppResponse) String() string { return proto.CompactTextString(m) }
func (*InitMconfigAppResponse) ProtoMessage()    {}
func (*InitMconfigAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1717ceaaafb7e16a, []int{3}
}

func (m *InitMconfigAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitMconfigAppResponse.Unmarshal(m, b)
}
func (m *InitMconfigAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitMconfigAppResponse.Marshal(b, m, deterministic)
}
func (m *InitMconfigAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitMconfigAppResponse.Merge(m, src)
}
func (m *InitMconfigAppResponse) XXX_Size() int {
	return xxx_messageInfo_InitMconfigAppResponse.Size(m)
}
func (m *InitMconfigAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitMconfigAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitMconfigAppResponse proto.InternalMessageInfo

func (m *InitMconfigAppResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *InitMconfigAppResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type UpdateMconfigAppRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	AppDesc              string   `protobuf:"bytes,2,opt,name=app_desc,json=appDesc,proto3" json:"app_desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMconfigAppRequest) Reset()         { *m = UpdateMconfigAppRequest{} }
func (m *UpdateMconfigAppRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMconfigAppRequest) ProtoMessage()    {}
func (*UpdateMconfigAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1717ceaaafb7e16a, []int{4}
}

func (m *UpdateMconfigAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMconfigAppRequest.Unmarshal(m, b)
}
func (m *UpdateMconfigAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMconfigAppRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMconfigAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMconfigAppRequest.Merge(m, src)
}
func (m *UpdateMconfigAppRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMconfigAppRequest.Size(m)
}
func (m *UpdateMconfigAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMconfigAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMconfigAppRequest proto.InternalMessageInfo

func (m *UpdateMconfigAppRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *UpdateMconfigAppRequest) GetAppDesc() string {
	if m != nil {
		return m.AppDesc
	}
	return ""
}

type UpdateMconfigAppResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMconfigAppResponse) Reset()         { *m = UpdateMconfigAppResponse{} }
func (m *UpdateMconfigAppResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateMconfigAppResponse) ProtoMessage()    {}
func (*UpdateMconfigAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1717ceaaafb7e16a, []int{5}
}

func (m *UpdateMconfigAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMconfigAppResponse.Unmarshal(m, b)
}
func (m *UpdateMconfigAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMconfigAppResponse.Marshal(b, m, deterministic)
}
func (m *UpdateMconfigAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMconfigAppResponse.Merge(m, src)
}
func (m *UpdateMconfigAppResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateMconfigAppResponse.Size(m)
}
func (m *UpdateMconfigAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMconfigAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMconfigAppResponse proto.InternalMessageInfo

func (m *UpdateMconfigAppResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UpdateMconfigAppResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DeleteMconfigConfigRequest struct {
	ConfigKey            string   `protobuf:"bytes,1,opt,name=config_key,json=configKey,proto3" json:"config_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMconfigConfigRequest) Reset()         { *m = DeleteMconfigConfigRequest{} }
func (m *DeleteMconfigConfigRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMconfigConfigRequest) ProtoMessage()    {}
func (*DeleteMconfigConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1717ceaaafb7e16a, []int{6}
}

func (m *DeleteMconfigConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMconfigConfigRequest.Unmarshal(m, b)
}
func (m *DeleteMconfigConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMconfigConfigRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMconfigConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMconfigConfigRequest.Merge(m, src)
}
func (m *DeleteMconfigConfigRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMconfigConfigRequest.Size(m)
}
func (m *DeleteMconfigConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMconfigConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMconfigConfigRequest proto.InternalMessageInfo

func (m *DeleteMconfigConfigRequest) GetConfigKey() string {
	if m != nil {
		return m.ConfigKey
	}
	return ""
}

type DeleteMconfigConfigResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMconfigConfigResponse) Reset()         { *m = DeleteMconfigConfigResponse{} }
func (m *DeleteMconfigConfigResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMconfigConfigResponse) ProtoMessage()    {}
func (*DeleteMconfigConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1717ceaaafb7e16a, []int{7}
}

func (m *DeleteMconfigConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMconfigConfigResponse.Unmarshal(m, b)
}
func (m *DeleteMconfigConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMconfigConfigResponse.Marshal(b, m, deterministic)
}
func (m *DeleteMconfigConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMconfigConfigResponse.Merge(m, src)
}
func (m *DeleteMconfigConfigResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMconfigConfigResponse.Size(m)
}
func (m *DeleteMconfigConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMconfigConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMconfigConfigResponse proto.InternalMessageInfo

func (m *DeleteMconfigConfigResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DeleteMconfigConfigResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DeleteMconfigAppRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMconfigAppRequest) Reset()         { *m = DeleteMconfigAppRequest{} }
func (m *DeleteMconfigAppRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMconfigAppRequest) ProtoMessage()    {}
func (*DeleteMconfigAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1717ceaaafb7e16a, []int{8}
}

func (m *DeleteMconfigAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMconfigAppRequest.Unmarshal(m, b)
}
func (m *DeleteMconfigAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMconfigAppRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMconfigAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMconfigAppRequest.Merge(m, src)
}
func (m *DeleteMconfigAppRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMconfigAppRequest.Size(m)
}
func (m *DeleteMconfigAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMconfigAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMconfigAppRequest proto.InternalMessageInfo

func (m *DeleteMconfigAppRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

type DeleteMconfigAppResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMconfigAppResponse) Reset()         { *m = DeleteMconfigAppResponse{} }
func (m *DeleteMconfigAppResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMconfigAppResponse) ProtoMessage()    {}
func (*DeleteMconfigAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1717ceaaafb7e16a, []int{9}
}

func (m *DeleteMconfigAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMconfigAppResponse.Unmarshal(m, b)
}
func (m *DeleteMconfigAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMconfigAppResponse.Marshal(b, m, deterministic)
}
func (m *DeleteMconfigAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMconfigAppResponse.Merge(m, src)
}
func (m *DeleteMconfigAppResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMconfigAppResponse.Size(m)
}
func (m *DeleteMconfigAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMconfigAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMconfigAppResponse proto.InternalMessageInfo

func (m *DeleteMconfigAppResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DeleteMconfigAppResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*PutMconfigRequest)(nil), "api.sdk.PutMconfigRequest")
	proto.RegisterType((*PutMconfigResponse)(nil), "api.sdk.PutMconfigResponse")
	proto.RegisterType((*InitMconfigAppRequest)(nil), "api.sdk.InitMconfigAppRequest")
	proto.RegisterType((*InitMconfigAppResponse)(nil), "api.sdk.InitMconfigAppResponse")
	proto.RegisterType((*UpdateMconfigAppRequest)(nil), "api.sdk.UpdateMconfigAppRequest")
	proto.RegisterType((*UpdateMconfigAppResponse)(nil), "api.sdk.UpdateMconfigAppResponse")
	proto.RegisterType((*DeleteMconfigConfigRequest)(nil), "api.sdk.DeleteMconfigConfigRequest")
	proto.RegisterType((*DeleteMconfigConfigResponse)(nil), "api.sdk.DeleteMconfigConfigResponse")
	proto.RegisterType((*DeleteMconfigAppRequest)(nil), "api.sdk.DeleteMconfigAppRequest")
	proto.RegisterType((*DeleteMconfigAppResponse)(nil), "api.sdk.DeleteMconfigAppResponse")
}

func init() { proto.RegisterFile("proto/v1/cli.proto", fileDescriptor_1717ceaaafb7e16a) }

var fileDescriptor_1717ceaaafb7e16a = []byte{
	// 481 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x5d, 0xe8, 0x96, 0xae, 0xf7, 0x61, 0x2a, 0x17, 0x6d, 0x35, 0xa9, 0x80, 0x12, 0x78, 0x18,
	0x42, 0x24, 0x50, 0xde, 0x40, 0x42, 0x40, 0x27, 0x24, 0x34, 0x55, 0x42, 0x9d, 0x78, 0x80, 0x97,
	0xc9, 0x49, 0xbd, 0xd6, 0x5a, 0xd2, 0x98, 0xd9, 0x45, 0xda, 0x2f, 0xf2, 0x11, 0x7c, 0x0b, 0xb2,
	0x5d, 0xb2, 0x26, 0x4d, 0x0a, 0x91, 0xf6, 0x10, 0xc9, 0xf6, 0x39, 0xf7, 0xe4, 0xdc, 0x9b, 0x13,
	0x03, 0x8a, 0xab, 0x4c, 0x65, 0xe1, 0xcf, 0x57, 0x61, 0x9c, 0xf0, 0xc0, 0x6c, 0xb0, 0x4d, 0x05,
	0x0f, 0xe4, 0xf4, 0xd2, 0x3b, 0xbc, 0x01, 0xb3, 0x34, 0xcd, 0x16, 0x16, 0xf7, 0x7f, 0x3b, 0x70,
	0xf7, 0xcb, 0x52, 0x8d, 0xe3, 0x6c, 0x71, 0xc1, 0x67, 0x13, 0xf6, 0x63, 0xc9, 0xa4, 0xc2, 0x1e,
	0xb4, 0xa9, 0x10, 0xe7, 0x97, 0xec, 0x9a, 0x38, 0x03, 0xe7, 0xb8, 0x33, 0x71, 0xa9, 0x10, 0xa7,
	0xec, 0x1a, 0x1f, 0x00, 0x58, 0xa6, 0xc1, 0xee, 0x18, 0xac, 0x63, 0x4f, 0x34, 0x7c, 0x04, 0xae,
	0x8c, 0xe7, 0x2c, 0xa5, 0xa4, 0x65, 0xcb, 0xec, 0x4e, 0x9f, 0x5b, 0x12, 0xd9, 0xb5, 0xe7, 0x76,
	0x87, 0x7d, 0xe8, 0xd0, 0xe8, 0xfc, 0x82, 0x27, 0x8a, 0x5d, 0x91, 0x3d, 0x03, 0xed, 0xd3, 0xe8,
	0x93, 0xd9, 0xe3, 0x4b, 0x70, 0xa5, 0xa2, 0x6a, 0x29, 0x89, 0x3b, 0x70, 0x8e, 0x0f, 0x86, 0x24,
	0xd0, 0xbd, 0xac, 0xdc, 0x8f, 0x8c, 0xc0, 0x99, 0xc1, 0x27, 0x2b, 0x1e, 0x22, 0xec, 0x4e, 0x99,
	0x8c, 0x49, 0xdb, 0x28, 0x99, 0xb5, 0xff, 0x06, 0x70, 0xbd, 0x3f, 0x29, 0xb2, 0x85, 0x64, 0x9a,
	0x19, 0x67, 0x53, 0x66, 0xba, 0xdb, 0x9b, 0x98, 0x35, 0x76, 0xa1, 0x95, 0xca, 0xd9, 0xaa, 0x29,
	0xbd, 0xf4, 0x4f, 0xe1, 0xf0, 0xf3, 0x82, 0xff, 0x2d, 0xfe, 0x20, 0xc4, 0x3f, 0xe7, 0x73, 0x1f,
	0xf6, 0x35, 0x60, 0x5c, 0x58, 0x21, 0x4d, 0x3c, 0xd1, 0x46, 0xde, 0xc1, 0x51, 0x59, 0xac, 0x91,
	0x99, 0x31, 0xf4, 0xbe, 0x8a, 0x29, 0x55, 0xec, 0x76, 0xec, 0xbc, 0x07, 0xb2, 0x29, 0xd7, 0xc8,
	0xd0, 0x5b, 0xf0, 0x4e, 0x58, 0xc2, 0x72, 0x85, 0x51, 0x21, 0x42, 0xc5, 0xa4, 0x38, 0xa5, 0xa4,
	0xf8, 0x23, 0xe8, 0x57, 0x16, 0x37, 0x72, 0x30, 0x84, 0x5e, 0x41, 0xe4, 0x3f, 0x46, 0xa2, 0xfb,
	0xde, 0xac, 0x69, 0xf2, 0xd6, 0xe1, 0xaf, 0x16, 0xc0, 0xd8, 0xfa, 0x1d, 0x25, 0x1c, 0xc7, 0xd0,
	0xbd, 0x09, 0x98, 0x3d, 0x46, 0x2f, 0x58, 0xfd, 0x76, 0xc1, 0xc6, 0xbf, 0xe5, 0xf5, 0x2b, 0x31,
	0xeb, 0xc0, 0xdf, 0xc1, 0x08, 0xee, 0x55, 0x0c, 0x06, 0x9f, 0xe4, 0x55, 0xf5, 0x33, 0xf7, 0x9e,
	0x6e, 0x27, 0xe5, 0xef, 0x38, 0x83, 0x83, 0x62, 0x14, 0xf1, 0x61, 0x5e, 0x59, 0x19, 0x78, 0xef,
	0x51, 0x2d, 0x9e, 0x8b, 0x7e, 0x83, 0x6e, 0x39, 0x50, 0x38, 0xc8, 0xcb, 0x6a, 0xa2, 0xeb, 0x3d,
	0xde, 0xc2, 0x58, 0x97, 0x2e, 0x7f, 0xb3, 0x35, 0xe9, 0x9a, 0x08, 0xac, 0x49, 0xd7, 0x7d, 0x70,
	0x7f, 0xe7, 0xe3, 0xf3, 0xef, 0xcf, 0x66, 0x5c, 0xcd, 0x97, 0x91, 0xbe, 0x58, 0xc2, 0x74, 0x1e,
	0xcf, 0x13, 0x1e, 0x85, 0xa9, 0xa5, 0xbe, 0xa0, 0x82, 0x87, 0xfa, 0xb1, 0x57, 0x6a, 0xe4, 0x9a,
	0x3b, 0xf3, 0xf5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x0d, 0x5c, 0xbf, 0x69, 0x05, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MConfigCliClient is the client API for MConfigCli service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MConfigCliClient interface {
	PutMconfigConfig(ctx context.Context, in *PutMconfigRequest, opts ...grpc.CallOption) (*PutMconfigResponse, error)
	DeleteMconfigConfig(ctx context.Context, in *DeleteMconfigConfigRequest, opts ...grpc.CallOption) (*DeleteMconfigConfigResponse, error)
	InitMconfigApp(ctx context.Context, in *InitMconfigAppRequest, opts ...grpc.CallOption) (*InitMconfigAppResponse, error)
	UpdateMconfigApp(ctx context.Context, in *UpdateMconfigAppRequest, opts ...grpc.CallOption) (*UpdateMconfigAppResponse, error)
	DeleteMconfigApp(ctx context.Context, in *DeleteMconfigAppRequest, opts ...grpc.CallOption) (*DeleteMconfigAppResponse, error)
}

type mConfigCliClient struct {
	cc *grpc.ClientConn
}

func NewMConfigCliClient(cc *grpc.ClientConn) MConfigCliClient {
	return &mConfigCliClient{cc}
}

func (c *mConfigCliClient) PutMconfigConfig(ctx context.Context, in *PutMconfigRequest, opts ...grpc.CallOption) (*PutMconfigResponse, error) {
	out := new(PutMconfigResponse)
	err := c.cc.Invoke(ctx, "/api.sdk.MConfigCli/PutMconfigConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mConfigCliClient) DeleteMconfigConfig(ctx context.Context, in *DeleteMconfigConfigRequest, opts ...grpc.CallOption) (*DeleteMconfigConfigResponse, error) {
	out := new(DeleteMconfigConfigResponse)
	err := c.cc.Invoke(ctx, "/api.sdk.MConfigCli/DeleteMconfigConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mConfigCliClient) InitMconfigApp(ctx context.Context, in *InitMconfigAppRequest, opts ...grpc.CallOption) (*InitMconfigAppResponse, error) {
	out := new(InitMconfigAppResponse)
	err := c.cc.Invoke(ctx, "/api.sdk.MConfigCli/InitMconfigApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mConfigCliClient) UpdateMconfigApp(ctx context.Context, in *UpdateMconfigAppRequest, opts ...grpc.CallOption) (*UpdateMconfigAppResponse, error) {
	out := new(UpdateMconfigAppResponse)
	err := c.cc.Invoke(ctx, "/api.sdk.MConfigCli/UpdateMconfigApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mConfigCliClient) DeleteMconfigApp(ctx context.Context, in *DeleteMconfigAppRequest, opts ...grpc.CallOption) (*DeleteMconfigAppResponse, error) {
	out := new(DeleteMconfigAppResponse)
	err := c.cc.Invoke(ctx, "/api.sdk.MConfigCli/DeleteMconfigApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MConfigCliServer is the server API for MConfigCli service.
type MConfigCliServer interface {
	PutMconfigConfig(context.Context, *PutMconfigRequest) (*PutMconfigResponse, error)
	DeleteMconfigConfig(context.Context, *DeleteMconfigConfigRequest) (*DeleteMconfigConfigResponse, error)
	InitMconfigApp(context.Context, *InitMconfigAppRequest) (*InitMconfigAppResponse, error)
	UpdateMconfigApp(context.Context, *UpdateMconfigAppRequest) (*UpdateMconfigAppResponse, error)
	DeleteMconfigApp(context.Context, *DeleteMconfigAppRequest) (*DeleteMconfigAppResponse, error)
}

// UnimplementedMConfigCliServer can be embedded to have forward compatible implementations.
type UnimplementedMConfigCliServer struct {
}

func (*UnimplementedMConfigCliServer) PutMconfigConfig(ctx context.Context, req *PutMconfigRequest) (*PutMconfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutMconfigConfig not implemented")
}
func (*UnimplementedMConfigCliServer) DeleteMconfigConfig(ctx context.Context, req *DeleteMconfigConfigRequest) (*DeleteMconfigConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMconfigConfig not implemented")
}
func (*UnimplementedMConfigCliServer) InitMconfigApp(ctx context.Context, req *InitMconfigAppRequest) (*InitMconfigAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitMconfigApp not implemented")
}
func (*UnimplementedMConfigCliServer) UpdateMconfigApp(ctx context.Context, req *UpdateMconfigAppRequest) (*UpdateMconfigAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMconfigApp not implemented")
}
func (*UnimplementedMConfigCliServer) DeleteMconfigApp(ctx context.Context, req *DeleteMconfigAppRequest) (*DeleteMconfigAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMconfigApp not implemented")
}

func RegisterMConfigCliServer(s *grpc.Server, srv MConfigCliServer) {
	s.RegisterService(&_MConfigCli_serviceDesc, srv)
}

func _MConfigCli_PutMconfigConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutMconfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MConfigCliServer).PutMconfigConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.sdk.MConfigCli/PutMconfigConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MConfigCliServer).PutMconfigConfig(ctx, req.(*PutMconfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MConfigCli_DeleteMconfigConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMconfigConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MConfigCliServer).DeleteMconfigConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.sdk.MConfigCli/DeleteMconfigConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MConfigCliServer).DeleteMconfigConfig(ctx, req.(*DeleteMconfigConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MConfigCli_InitMconfigApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitMconfigAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MConfigCliServer).InitMconfigApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.sdk.MConfigCli/InitMconfigApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MConfigCliServer).InitMconfigApp(ctx, req.(*InitMconfigAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MConfigCli_UpdateMconfigApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMconfigAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MConfigCliServer).UpdateMconfigApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.sdk.MConfigCli/UpdateMconfigApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MConfigCliServer).UpdateMconfigApp(ctx, req.(*UpdateMconfigAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MConfigCli_DeleteMconfigApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMconfigAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MConfigCliServer).DeleteMconfigApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.sdk.MConfigCli/DeleteMconfigApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MConfigCliServer).DeleteMconfigApp(ctx, req.(*DeleteMconfigAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MConfigCli_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.sdk.MConfigCli",
	HandlerType: (*MConfigCliServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutMconfigConfig",
			Handler:    _MConfigCli_PutMconfigConfig_Handler,
		},
		{
			MethodName: "DeleteMconfigConfig",
			Handler:    _MConfigCli_DeleteMconfigConfig_Handler,
		},
		{
			MethodName: "InitMconfigApp",
			Handler:    _MConfigCli_InitMconfigApp_Handler,
		},
		{
			MethodName: "UpdateMconfigApp",
			Handler:    _MConfigCli_UpdateMconfigApp_Handler,
		},
		{
			MethodName: "DeleteMconfigApp",
			Handler:    _MConfigCli_DeleteMconfigApp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/cli.proto",
}
