// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: proto/v1/cli.proto

package cli

import (
	proto "github.com/golang/protobuf/proto"
	common "github.com/mhchlib/mconfig-api/api/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PutMconfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppKey    string              `protobuf:"bytes,1,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	ConfigKey string              `protobuf:"bytes,2,opt,name=config_key,json=configKey,proto3" json:"config_key,omitempty"`
	Schema    string              `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	Config    string              `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	AbFilter  string              `protobuf:"bytes,5,opt,name=ab_filter,json=abFilter,proto3" json:"ab_filter,omitempty"`
	Status    common.ConfigStatus `protobuf:"varint,6,opt,name=status,proto3,enum=api.common.ConfigStatus" json:"status,omitempty"`
	Desc      string              `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
}

func (x *PutMconfigRequest) Reset() {
	*x = PutMconfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_cli_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutMconfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutMconfigRequest) ProtoMessage() {}

func (x *PutMconfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_cli_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutMconfigRequest.ProtoReflect.Descriptor instead.
func (*PutMconfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_cli_proto_rawDescGZIP(), []int{0}
}

func (x *PutMconfigRequest) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *PutMconfigRequest) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

func (x *PutMconfigRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *PutMconfigRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *PutMconfigRequest) GetAbFilter() string {
	if x != nil {
		return x.AbFilter
	}
	return ""
}

func (x *PutMconfigRequest) GetStatus() common.ConfigStatus {
	if x != nil {
		return x.Status
	}
	return common.ConfigStatus_Unpublished
}

func (x *PutMconfigRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type PutMconfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *PutMconfigResponse) Reset() {
	*x = PutMconfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_cli_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutMconfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutMconfigResponse) ProtoMessage() {}

func (x *PutMconfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_cli_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutMconfigResponse.ProtoReflect.Descriptor instead.
func (*PutMconfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_cli_proto_rawDescGZIP(), []int{1}
}

func (x *PutMconfigResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PutMconfigResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type InitMconfigAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppKey  string `protobuf:"bytes,1,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	AppDesc string `protobuf:"bytes,2,opt,name=app_desc,json=appDesc,proto3" json:"app_desc,omitempty"`
}

func (x *InitMconfigAppRequest) Reset() {
	*x = InitMconfigAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_cli_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitMconfigAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitMconfigAppRequest) ProtoMessage() {}

func (x *InitMconfigAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_cli_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitMconfigAppRequest.ProtoReflect.Descriptor instead.
func (*InitMconfigAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_cli_proto_rawDescGZIP(), []int{2}
}

func (x *InitMconfigAppRequest) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *InitMconfigAppRequest) GetAppDesc() string {
	if x != nil {
		return x.AppDesc
	}
	return ""
}

type InitMconfigAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *InitMconfigAppResponse) Reset() {
	*x = InitMconfigAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_cli_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitMconfigAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitMconfigAppResponse) ProtoMessage() {}

func (x *InitMconfigAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_cli_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitMconfigAppResponse.ProtoReflect.Descriptor instead.
func (*InitMconfigAppResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_cli_proto_rawDescGZIP(), []int{3}
}

func (x *InitMconfigAppResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InitMconfigAppResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateMconfigAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppKey  string `protobuf:"bytes,1,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	AppDesc string `protobuf:"bytes,2,opt,name=app_desc,json=appDesc,proto3" json:"app_desc,omitempty"`
}

func (x *UpdateMconfigAppRequest) Reset() {
	*x = UpdateMconfigAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_cli_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMconfigAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMconfigAppRequest) ProtoMessage() {}

func (x *UpdateMconfigAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_cli_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMconfigAppRequest.ProtoReflect.Descriptor instead.
func (*UpdateMconfigAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_cli_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMconfigAppRequest) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *UpdateMconfigAppRequest) GetAppDesc() string {
	if x != nil {
		return x.AppDesc
	}
	return ""
}

type UpdateMconfigAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *UpdateMconfigAppResponse) Reset() {
	*x = UpdateMconfigAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_cli_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMconfigAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMconfigAppResponse) ProtoMessage() {}

func (x *UpdateMconfigAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_cli_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMconfigAppResponse.ProtoReflect.Descriptor instead.
func (*UpdateMconfigAppResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_cli_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMconfigAppResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateMconfigAppResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DeleteMconfigConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigKey string `protobuf:"bytes,1,opt,name=config_key,json=configKey,proto3" json:"config_key,omitempty"`
}

func (x *DeleteMconfigConfigRequest) Reset() {
	*x = DeleteMconfigConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_cli_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMconfigConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMconfigConfigRequest) ProtoMessage() {}

func (x *DeleteMconfigConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_cli_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMconfigConfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteMconfigConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_cli_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteMconfigConfigRequest) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

type DeleteMconfigConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DeleteMconfigConfigResponse) Reset() {
	*x = DeleteMconfigConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_cli_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMconfigConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMconfigConfigResponse) ProtoMessage() {}

func (x *DeleteMconfigConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_cli_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMconfigConfigResponse.ProtoReflect.Descriptor instead.
func (*DeleteMconfigConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_cli_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMconfigConfigResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteMconfigConfigResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DeleteMconfigAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppKey string `protobuf:"bytes,1,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
}

func (x *DeleteMconfigAppRequest) Reset() {
	*x = DeleteMconfigAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_cli_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMconfigAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMconfigAppRequest) ProtoMessage() {}

func (x *DeleteMconfigAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_cli_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMconfigAppRequest.ProtoReflect.Descriptor instead.
func (*DeleteMconfigAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_cli_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMconfigAppRequest) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

type DeleteMconfigAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DeleteMconfigAppResponse) Reset() {
	*x = DeleteMconfigAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_cli_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMconfigAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMconfigAppResponse) ProtoMessage() {}

func (x *DeleteMconfigAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_cli_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMconfigAppResponse.ProtoReflect.Descriptor instead.
func (*DeleteMconfigAppResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_cli_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMconfigAppResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteMconfigAppResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_v1_cli_proto protoreflect.FileDescriptor

var file_proto_v1_cli_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6c, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x64, 0x6b, 0x1a, 0x15, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xde, 0x01, 0x0a, 0x11, 0x50, 0x75, 0x74, 0x4d, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x70,
	0x70, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x70,
	0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4b,
	0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x62, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x62, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12,
	0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x22, 0x3a, 0x0a, 0x12, 0x50, 0x75, 0x74, 0x4d, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0x4b, 0x0a, 0x15, 0x49, 0x6e, 0x69, 0x74, 0x4d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x70,
	0x70, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x70,
	0x4b, 0x65, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x44, 0x65, 0x73, 0x63, 0x22, 0x3e,
	0x0a, 0x16, 0x49, 0x6e, 0x69, 0x74, 0x4d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x70, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x4d,
	0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41,
	0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x70, 0x70,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x70, 0x4b,
	0x65, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x44, 0x65, 0x73, 0x63, 0x22, 0x40, 0x0a,
	0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x70,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22,
	0x3b, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4b, 0x65, 0x79, 0x22, 0x43, 0x0a, 0x1b,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0x32, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x61, 0x70, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x70, 0x70, 0x4b, 0x65, 0x79, 0x22, 0x40, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0xca, 0x03, 0x0a, 0x0a, 0x4d, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x43, 0x6c, 0x69, 0x12, 0x4d, 0x0a, 0x10, 0x50, 0x75, 0x74, 0x4d, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x50, 0x75, 0x74, 0x4d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x64, 0x6b,
	0x2e, 0x50, 0x75, 0x74, 0x4d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x23, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0e, 0x49, 0x6e, 0x69,
	0x74, 0x4d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x70, 0x70, 0x12, 0x1e, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x4d, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x4d, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59,
	0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41,
	0x70, 0x70, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x70, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x10, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x70, 0x70, 0x12, 0x20, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x68, 0x63, 0x68, 0x6c, 0x69, 0x62, 0x2f, 0x6d, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6c,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_v1_cli_proto_rawDescOnce sync.Once
	file_proto_v1_cli_proto_rawDescData = file_proto_v1_cli_proto_rawDesc
)

func file_proto_v1_cli_proto_rawDescGZIP() []byte {
	file_proto_v1_cli_proto_rawDescOnce.Do(func() {
		file_proto_v1_cli_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v1_cli_proto_rawDescData)
	})
	return file_proto_v1_cli_proto_rawDescData
}

var file_proto_v1_cli_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_v1_cli_proto_goTypes = []interface{}{
	(*PutMconfigRequest)(nil),           // 0: api.sdk.PutMconfigRequest
	(*PutMconfigResponse)(nil),          // 1: api.sdk.PutMconfigResponse
	(*InitMconfigAppRequest)(nil),       // 2: api.sdk.InitMconfigAppRequest
	(*InitMconfigAppResponse)(nil),      // 3: api.sdk.InitMconfigAppResponse
	(*UpdateMconfigAppRequest)(nil),     // 4: api.sdk.UpdateMconfigAppRequest
	(*UpdateMconfigAppResponse)(nil),    // 5: api.sdk.UpdateMconfigAppResponse
	(*DeleteMconfigConfigRequest)(nil),  // 6: api.sdk.DeleteMconfigConfigRequest
	(*DeleteMconfigConfigResponse)(nil), // 7: api.sdk.DeleteMconfigConfigResponse
	(*DeleteMconfigAppRequest)(nil),     // 8: api.sdk.DeleteMconfigAppRequest
	(*DeleteMconfigAppResponse)(nil),    // 9: api.sdk.DeleteMconfigAppResponse
	(common.ConfigStatus)(0),            // 10: api.common.ConfigStatus
}
var file_proto_v1_cli_proto_depIdxs = []int32{
	10, // 0: api.sdk.PutMconfigRequest.status:type_name -> api.common.ConfigStatus
	0,  // 1: api.sdk.MConfigCli.PutMconfigConfig:input_type -> api.sdk.PutMconfigRequest
	6,  // 2: api.sdk.MConfigCli.DeleteMconfigConfig:input_type -> api.sdk.DeleteMconfigConfigRequest
	2,  // 3: api.sdk.MConfigCli.InitMconfigApp:input_type -> api.sdk.InitMconfigAppRequest
	4,  // 4: api.sdk.MConfigCli.UpdateMconfigApp:input_type -> api.sdk.UpdateMconfigAppRequest
	8,  // 5: api.sdk.MConfigCli.DeleteMconfigApp:input_type -> api.sdk.DeleteMconfigAppRequest
	1,  // 6: api.sdk.MConfigCli.PutMconfigConfig:output_type -> api.sdk.PutMconfigResponse
	7,  // 7: api.sdk.MConfigCli.DeleteMconfigConfig:output_type -> api.sdk.DeleteMconfigConfigResponse
	3,  // 8: api.sdk.MConfigCli.InitMconfigApp:output_type -> api.sdk.InitMconfigAppResponse
	5,  // 9: api.sdk.MConfigCli.UpdateMconfigApp:output_type -> api.sdk.UpdateMconfigAppResponse
	9,  // 10: api.sdk.MConfigCli.DeleteMconfigApp:output_type -> api.sdk.DeleteMconfigAppResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_v1_cli_proto_init() }
func file_proto_v1_cli_proto_init() {
	if File_proto_v1_cli_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_v1_cli_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutMconfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_cli_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutMconfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_cli_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitMconfigAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_cli_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitMconfigAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_cli_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMconfigAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_cli_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMconfigAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_cli_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMconfigConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_cli_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMconfigConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_cli_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMconfigAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_cli_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMconfigAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v1_cli_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_cli_proto_goTypes,
		DependencyIndexes: file_proto_v1_cli_proto_depIdxs,
		MessageInfos:      file_proto_v1_cli_proto_msgTypes,
	}.Build()
	File_proto_v1_cli_proto = out.File
	file_proto_v1_cli_proto_rawDesc = nil
	file_proto_v1_cli_proto_goTypes = nil
	file_proto_v1_cli_proto_depIdxs = nil
}
