// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/sdk.proto

package sdk

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/mhchlib/mconfig-api/api/v1/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExtraData struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtraData) Reset()         { *m = ExtraData{} }
func (m *ExtraData) String() string { return proto.CompactTextString(m) }
func (*ExtraData) ProtoMessage()    {}
func (*ExtraData) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc06ddaf5f58ac25, []int{0}
}

func (m *ExtraData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtraData.Unmarshal(m, b)
}
func (m *ExtraData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtraData.Marshal(b, m, deterministic)
}
func (m *ExtraData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtraData.Merge(m, src)
}
func (m *ExtraData) XXX_Size() int {
	return xxx_messageInfo_ExtraData.Size(m)
}
func (m *ExtraData) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtraData.DiscardUnknown(m)
}

var xxx_messageInfo_ExtraData proto.InternalMessageInfo

func (m *ExtraData) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ExtraData) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetVRequest struct {
	AppId                string         `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Filters              *ConfigFilters `protobuf:"bytes,2,opt,name=filters,proto3" json:"filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetVRequest) Reset()         { *m = GetVRequest{} }
func (m *GetVRequest) String() string { return proto.CompactTextString(m) }
func (*GetVRequest) ProtoMessage()    {}
func (*GetVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc06ddaf5f58ac25, []int{1}
}

func (m *GetVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVRequest.Unmarshal(m, b)
}
func (m *GetVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVRequest.Marshal(b, m, deterministic)
}
func (m *GetVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVRequest.Merge(m, src)
}
func (m *GetVRequest) XXX_Size() int {
	return xxx_messageInfo_GetVRequest.Size(m)
}
func (m *GetVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVRequest proto.InternalMessageInfo

func (m *GetVRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *GetVRequest) GetFilters() *ConfigFilters {
	if m != nil {
		return m.Filters
	}
	return nil
}

type ConfigFilters struct {
	ConfigIds            []string          `protobuf:"bytes,2,rep,name=config_ids,json=configIds,proto3" json:"config_ids,omitempty"`
	ExtraData            map[string]string `protobuf:"bytes,3,rep,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ConfigFilters) Reset()         { *m = ConfigFilters{} }
func (m *ConfigFilters) String() string { return proto.CompactTextString(m) }
func (*ConfigFilters) ProtoMessage()    {}
func (*ConfigFilters) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc06ddaf5f58ac25, []int{2}
}

func (m *ConfigFilters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigFilters.Unmarshal(m, b)
}
func (m *ConfigFilters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigFilters.Marshal(b, m, deterministic)
}
func (m *ConfigFilters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigFilters.Merge(m, src)
}
func (m *ConfigFilters) XXX_Size() int {
	return xxx_messageInfo_ConfigFilters.Size(m)
}
func (m *ConfigFilters) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigFilters.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigFilters proto.InternalMessageInfo

func (m *ConfigFilters) GetConfigIds() []string {
	if m != nil {
		return m.ConfigIds
	}
	return nil
}

func (m *ConfigFilters) GetExtraData() map[string]string {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

type Config struct {
	Id                   string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Schema               string              `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Config               string              `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Status               common.ConfigStatus `protobuf:"varint,4,opt,name=status,proto3,enum=api.common.ConfigStatus" json:"status,omitempty"`
	Desc                 string              `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	CreateTime           int64               `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           int64               `protobuf:"varint,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc06ddaf5f58ac25, []int{3}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Config) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func (m *Config) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

func (m *Config) GetStatus() common.ConfigStatus {
	if m != nil {
		return m.Status
	}
	return common.ConfigStatus_Unpublished
}

func (m *Config) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Config) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Config) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type GetVResponse struct {
	Configs              []*Config `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetVResponse) Reset()         { *m = GetVResponse{} }
func (m *GetVResponse) String() string { return proto.CompactTextString(m) }
func (*GetVResponse) ProtoMessage()    {}
func (*GetVResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc06ddaf5f58ac25, []int{4}
}

func (m *GetVResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVResponse.Unmarshal(m, b)
}
func (m *GetVResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVResponse.Marshal(b, m, deterministic)
}
func (m *GetVResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVResponse.Merge(m, src)
}
func (m *GetVResponse) XXX_Size() int {
	return xxx_messageInfo_GetVResponse.Size(m)
}
func (m *GetVResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVResponse proto.InternalMessageInfo

func (m *GetVResponse) GetConfigs() []*Config {
	if m != nil {
		return m.Configs
	}
	return nil
}

func init() {
	proto.RegisterType((*ExtraData)(nil), "api.sdk.ExtraData")
	proto.RegisterType((*GetVRequest)(nil), "api.sdk.GetVRequest")
	proto.RegisterType((*ConfigFilters)(nil), "api.sdk.ConfigFilters")
	proto.RegisterMapType((map[string]string)(nil), "api.sdk.ConfigFilters.ExtraDataEntry")
	proto.RegisterType((*Config)(nil), "api.sdk.Config")
	proto.RegisterType((*GetVResponse)(nil), "api.sdk.GetVResponse")
}

func init() { proto.RegisterFile("proto/v1/sdk.proto", fileDescriptor_dc06ddaf5f58ac25) }

var fileDescriptor_dc06ddaf5f58ac25 = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x5f, 0x6b, 0xdb, 0x30,
	0x10, 0x9f, 0xe2, 0xc6, 0xc1, 0x97, 0x2d, 0x1b, 0xa2, 0x29, 0x22, 0x30, 0x16, 0x0c, 0x03, 0x97,
	0x31, 0x3b, 0x4b, 0x5f, 0xb6, 0x31, 0x18, 0x6c, 0xed, 0x46, 0x07, 0x7b, 0x71, 0x47, 0x1e, 0xf6,
	0x12, 0x14, 0x4b, 0x6d, 0x44, 0xe2, 0x58, 0xb3, 0xe4, 0xb2, 0x7e, 0xad, 0x7d, 0x92, 0x7d, 0xa4,
	0x22, 0x9d, 0x63, 0xda, 0xd2, 0x07, 0x83, 0x7f, 0x7f, 0x4e, 0xa7, 0xfb, 0xe9, 0x80, 0xea, 0xba,
	0xb2, 0x55, 0x76, 0xfd, 0x2e, 0x33, 0x62, 0x93, 0x7a, 0x40, 0x07, 0x5c, 0xab, 0xd4, 0x88, 0xcd,
	0x64, 0xdc, 0x89, 0x45, 0x55, 0x96, 0xd5, 0x0e, 0xf5, 0xf8, 0x04, 0xa2, 0xb3, 0xbf, 0xb6, 0xe6,
	0xa7, 0xdc, 0x72, 0xfa, 0x02, 0x82, 0x8d, 0xbc, 0x61, 0x64, 0x4a, 0x92, 0x28, 0x77, 0xbf, 0xf4,
	0x10, 0xfa, 0x0b, 0xbe, 0x6d, 0x24, 0xeb, 0x79, 0x0e, 0x41, 0xbc, 0x80, 0xe1, 0x77, 0x69, 0x17,
	0xb9, 0xfc, 0xd3, 0x48, 0x63, 0xe9, 0x18, 0x42, 0xae, 0xf5, 0x52, 0x89, 0xb6, 0xb2, 0xcf, 0xb5,
	0x3e, 0x17, 0x74, 0x06, 0x83, 0x4b, 0xb5, 0xb5, 0xb2, 0x36, 0xbe, 0x7a, 0x38, 0x3f, 0x4a, 0xdb,
	0xcb, 0xa4, 0x5f, 0xab, 0xdd, 0xa5, 0xba, 0xfa, 0x86, 0x6a, 0xbe, 0xb7, 0xc5, 0xff, 0x08, 0x3c,
	0xbb, 0x27, 0xd1, 0x97, 0x00, 0x85, 0x27, 0x96, 0x4a, 0xb8, 0x63, 0x82, 0x24, 0xca, 0x23, 0x64,
	0xce, 0x85, 0xa1, 0xa7, 0x00, 0xd2, 0xdd, 0x7e, 0x29, 0xb8, 0xe5, 0x2c, 0x98, 0x06, 0xc9, 0x70,
	0xfe, 0xfa, 0xf1, 0x2e, 0x69, 0x37, 0xe6, 0xd9, 0xce, 0xd6, 0x37, 0x79, 0x24, 0xf7, 0x78, 0xf2,
	0x09, 0x46, 0xf7, 0xc5, 0xc7, 0x83, 0xb8, 0xbe, 0x1b, 0x84, 0x07, 0x1f, 0x7b, 0xef, 0x49, 0xfc,
	0x9f, 0x40, 0x88, 0x9d, 0xe8, 0x08, 0x7a, 0x5d, 0x08, 0x3d, 0x25, 0xe8, 0x11, 0x84, 0xa6, 0x58,
	0xcb, 0x92, 0xb7, 0x55, 0x2d, 0x72, 0x3c, 0xce, 0xc0, 0x02, 0xe4, 0x11, 0xd1, 0x19, 0x84, 0xc6,
	0x72, 0xdb, 0x18, 0x76, 0x30, 0x25, 0xc9, 0x68, 0xce, 0xfc, 0x28, 0xed, 0x7b, 0x61, 0x8f, 0x0b,
	0xaf, 0xe7, 0xad, 0x8f, 0x52, 0x38, 0x10, 0xd2, 0x14, 0xac, 0xef, 0xcf, 0xf1, 0xff, 0xf4, 0x15,
	0x0c, 0x8b, 0x5a, 0x72, 0x2b, 0x97, 0x56, 0x95, 0x92, 0x85, 0x53, 0x92, 0x04, 0x39, 0x20, 0xf5,
	0x4b, 0x95, 0xd2, 0x19, 0x1a, 0x2d, 0x3a, 0xc3, 0x00, 0x0d, 0x48, 0x39, 0x43, 0xfc, 0x01, 0x9e,
	0xe2, 0xfb, 0x1a, 0x5d, 0xed, 0x8c, 0xa4, 0xc7, 0x30, 0xc0, 0x1b, 0x1a, 0x46, 0x7c, 0xc6, 0xcf,
	0x1f, 0x64, 0x9c, 0xef, 0xf5, 0xf9, 0x0f, 0x18, 0xfc, 0x6c, 0xd3, 0xf8, 0x0c, 0xe0, 0x4e, 0xb9,
	0xb0, 0xb5, 0xe4, 0x25, 0x3d, 0xec, 0x4a, 0xee, 0xac, 0xce, 0x64, 0xfc, 0x80, 0xc5, 0x86, 0xf1,
	0x93, 0x84, 0xcc, 0xc8, 0x97, 0x37, 0xbf, 0x8f, 0xaf, 0x94, 0x5d, 0x37, 0x2b, 0x17, 0x41, 0x56,
	0xae, 0x8b, 0xf5, 0x56, 0xad, 0xb2, 0x12, 0x5b, 0xbd, 0xe5, 0x5a, 0x65, 0xee, 0xc3, 0x75, 0x5f,
	0x85, 0x7e, 0x9f, 0x4f, 0x6e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x42, 0x3c, 0x91, 0x05, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MConfigClient is the client API for MConfig service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MConfigClient interface {
	GetVStream(ctx context.Context, opts ...grpc.CallOption) (MConfig_GetVStreamClient, error)
}

type mConfigClient struct {
	cc *grpc.ClientConn
}

func NewMConfigClient(cc *grpc.ClientConn) MConfigClient {
	return &mConfigClient{cc}
}

func (c *mConfigClient) GetVStream(ctx context.Context, opts ...grpc.CallOption) (MConfig_GetVStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MConfig_serviceDesc.Streams[0], "/api.sdk.MConfig/GetVStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &mConfigGetVStreamClient{stream}
	return x, nil
}

type MConfig_GetVStreamClient interface {
	Send(*GetVRequest) error
	Recv() (*GetVResponse, error)
	grpc.ClientStream
}

type mConfigGetVStreamClient struct {
	grpc.ClientStream
}

func (x *mConfigGetVStreamClient) Send(m *GetVRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mConfigGetVStreamClient) Recv() (*GetVResponse, error) {
	m := new(GetVResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MConfigServer is the server API for MConfig service.
type MConfigServer interface {
	GetVStream(MConfig_GetVStreamServer) error
}

// UnimplementedMConfigServer can be embedded to have forward compatible implementations.
type UnimplementedMConfigServer struct {
}

func (*UnimplementedMConfigServer) GetVStream(srv MConfig_GetVStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetVStream not implemented")
}

func RegisterMConfigServer(s *grpc.Server, srv MConfigServer) {
	s.RegisterService(&_MConfig_serviceDesc, srv)
}

func _MConfig_GetVStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MConfigServer).GetVStream(&mConfigGetVStreamServer{stream})
}

type MConfig_GetVStreamServer interface {
	Send(*GetVResponse) error
	Recv() (*GetVRequest, error)
	grpc.ServerStream
}

type mConfigGetVStreamServer struct {
	grpc.ServerStream
}

func (x *mConfigGetVStreamServer) Send(m *GetVResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mConfigGetVStreamServer) Recv() (*GetVRequest, error) {
	m := new(GetVRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _MConfig_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.sdk.MConfig",
	HandlerType: (*MConfigServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetVStream",
			Handler:       _MConfig_GetVStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/v1/sdk.proto",
}
