// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: proto/v1/sdk.proto

package sdk

import (
	proto "github.com/golang/protobuf/proto"
	common "github.com/mhchlib/mconfig-api/api/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetVRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId     string              `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ConfigId  []string            `protobuf:"bytes,2,rep,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	ExtraData []*common.ExtraData `protobuf:"bytes,3,rep,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
}

func (x *GetVRequest) Reset() {
	*x = GetVRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_sdk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVRequest) ProtoMessage() {}

func (x *GetVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sdk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVRequest.ProtoReflect.Descriptor instead.
func (*GetVRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_sdk_proto_rawDescGZIP(), []int{0}
}

func (x *GetVRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetVRequest) GetConfigId() []string {
	if x != nil {
		return x.ConfigId
	}
	return nil
}

func (x *GetVRequest) GetExtraData() []*common.ExtraData {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

type GetVResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configs []*common.ConfigEntityForClient `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
}

func (x *GetVResponse) Reset() {
	*x = GetVResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_sdk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVResponse) ProtoMessage() {}

func (x *GetVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sdk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVResponse.ProtoReflect.Descriptor instead.
func (*GetVResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_sdk_proto_rawDescGZIP(), []int{1}
}

func (x *GetVResponse) GetConfigs() []*common.ConfigEntityForClient {
	if x != nil {
		return x.Configs
	}
	return nil
}

var File_proto_v1_sdk_proto protoreflect.FileDescriptor

var file_proto_v1_sdk_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x64, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x64, 0x6b, 0x1a, 0x15, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x56, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x0a, 0x65, 0x78, 0x74, 0x72, 0x61,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x09, 0x65, 0x78, 0x74, 0x72, 0x61, 0x44, 0x61, 0x74, 0x61, 0x22, 0x4b, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x56, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x46, 0x6f, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x32, 0x48, 0x0a, 0x07, 0x4d, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x3d, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x56, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x12, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x47, 0x65,
	0x74, 0x56, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x64, 0x6b, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x68, 0x63, 0x68, 0x6c, 0x69, 0x62, 0x2f, 0x6d, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x64,
	0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_v1_sdk_proto_rawDescOnce sync.Once
	file_proto_v1_sdk_proto_rawDescData = file_proto_v1_sdk_proto_rawDesc
)

func file_proto_v1_sdk_proto_rawDescGZIP() []byte {
	file_proto_v1_sdk_proto_rawDescOnce.Do(func() {
		file_proto_v1_sdk_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v1_sdk_proto_rawDescData)
	})
	return file_proto_v1_sdk_proto_rawDescData
}

var file_proto_v1_sdk_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_v1_sdk_proto_goTypes = []interface{}{
	(*GetVRequest)(nil),                  // 0: api.sdk.GetVRequest
	(*GetVResponse)(nil),                 // 1: api.sdk.GetVResponse
	(*common.ExtraData)(nil),             // 2: api.common.ExtraData
	(*common.ConfigEntityForClient)(nil), // 3: api.common.ConfigEntityForClient
}
var file_proto_v1_sdk_proto_depIdxs = []int32{
	2, // 0: api.sdk.GetVRequest.extra_data:type_name -> api.common.ExtraData
	3, // 1: api.sdk.GetVResponse.configs:type_name -> api.common.ConfigEntityForClient
	0, // 2: api.sdk.MConfig.GetVStream:input_type -> api.sdk.GetVRequest
	1, // 3: api.sdk.MConfig.GetVStream:output_type -> api.sdk.GetVResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_v1_sdk_proto_init() }
func file_proto_v1_sdk_proto_init() {
	if File_proto_v1_sdk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_v1_sdk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_sdk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v1_sdk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_sdk_proto_goTypes,
		DependencyIndexes: file_proto_v1_sdk_proto_depIdxs,
		MessageInfos:      file_proto_v1_sdk_proto_msgTypes,
	}.Build()
	File_proto_v1_sdk_proto = out.File
	file_proto_v1_sdk_proto_rawDesc = nil
	file_proto_v1_sdk_proto_goTypes = nil
	file_proto_v1_sdk_proto_depIdxs = nil
}
